# Generated by Django 4.2.16 on 2024-09-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DiseaseDetection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="disease_images/")),
                ("prediction", models.CharField(max_length=255)),
                ("prob", models.CharField(max_length=255)),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
